project_id = "pnaiiwgjakqtwylmozvi"

[functions.office365-auth]
verify_jwt = true

[functions.office365-sync]
verify_jwt = true

[functions.hubspot-auth]
verify_jwt = true

[functions.hubspot-sync]
verify_jwt = true

[functions.workflow-trigger]
verify_jwt = false

[functions.scheduled-checks]
verify_jwt = false
