project_id = "pnaiiwgjakqtwylmozvi"

[functions.office365-auth]
verify_jwt = true

[functions.office365-sync]
verify_jwt = true

[functions.hubspot-auth]
verify_jwt = true

[functions.hubspot-sync]
verify_jwt = true

[functions.workflow-trigger]
verify_jwt = false

[functions.scheduled-checks]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.create-users]
verify_jwt = true

[functions.set-user-password]
verify_jwt = true

[functions.employee-assistant]
verify_jwt = true

[functions.sales-assistant]
verify_jwt = true
