project_id = "pnaiiwgjakqtwylmozvi"

[functions.office365-auth]
verify_jwt = true

[functions.office365-sync]
verify_jwt = true

[functions.hubspot-auth]
verify_jwt = true

[functions.hubspot-sync]
verify_jwt = true

[functions.workflow-trigger]
verify_jwt = false

[functions.scheduled-checks]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.create-users]
verify_jwt = true

[functions.set-user-password]
verify_jwt = true

[functions.employee-assistant]
verify_jwt = true

[functions.sales-assistant]
verify_jwt = true

[functions.fetch-company-info]
verify_jwt = false

[functions.enrich-company]
verify_jwt = false

[functions.threat-intelligence]
verify_jwt = false

[functions.enrich-user]
verify_jwt = false

[functions.account-intelligence]
verify_jwt = false

[functions.enrich-offering]
verify_jwt = true

[functions.enrich-executives]
verify_jwt = false

[functions.support-assistant]
verify_jwt = true

[functions.contact-intelligence]
verify_jwt = false

[functions.verify-document]
verify_jwt = true

[functions.enrich-problem-area]
verify_jwt = false

[functions.batch-enrich-offerings]
verify_jwt = false

[functions.generate-recommendation-steps]
verify_jwt = true

[functions.generate-solution-documentation]
verify_jwt = true
