import { createCrudRoutes } from './crud-factory.js';

// All table route configs - register these in server.ts
export const allRouteConfigs = [
  { prefix: '/api/contacts', config: { tableName: 'contacts', searchColumns: ['name', 'email', 'company'], userOwned: true } },
  { prefix: '/api/deals', config: { tableName: 'deals', searchColumns: ['title'], userOwned: true } },
  { prefix: '/api/tickets', config: { tableName: 'tickets', searchColumns: ['title', 'ticket_number'] } },
  { prefix: '/api/alliance-organizations', config: { tableName: 'alliance_organizations', searchColumns: ['name'] } },
  { prefix: '/api/alliance-users', config: { tableName: 'alliance_users', searchColumns: ['name', 'email'] } },
  { prefix: '/api/assets', config: { tableName: 'assets', searchColumns: ['name', 'asset_number'] } },
  { prefix: '/api/asset-categories', config: { tableName: 'asset_categories', searchColumns: ['name'] } },
  { prefix: '/api/asset-assignments', config: { tableName: 'asset_assignments' } },
  { prefix: '/api/asset-maintenance', config: { tableName: 'asset_maintenance' } },
  { prefix: '/api/attendance', config: { tableName: 'attendance', userOwned: true } },
  { prefix: '/api/attendance-activities', config: { tableName: 'attendance_activities', userOwned: true } },
  { prefix: '/api/activity-definitions', config: { tableName: 'activity_definitions', searchColumns: ['name'] } },
  { prefix: '/api/calendar-events', config: { tableName: 'calendar_events', searchColumns: ['title'], userOwned: true, userField: 'owner_id' } },
  { prefix: '/api/chat-conversations', config: { tableName: 'chat_conversations' } },
  { prefix: '/api/chat-messages', config: { tableName: 'chat_messages', tenantScoped: false } },
  { prefix: '/api/chat-participants', config: { tableName: 'chat_participants', tenantScoped: false } },
  { prefix: '/api/compliance-frameworks', config: { tableName: 'compliance_frameworks', searchColumns: ['name'] } },
  { prefix: '/api/compliance-controls', config: { tableName: 'compliance_controls', searchColumns: ['title'], tenantScoped: false } },
  { prefix: '/api/compliance-evidence', config: { tableName: 'compliance_evidence', tenantScoped: false } },
  { prefix: '/api/compliance-assessments', config: { tableName: 'compliance_assessments', tenantScoped: false } },
  { prefix: '/api/contractors', config: { tableName: 'contractors', searchColumns: ['name', 'email'] } },
  { prefix: '/api/quotations', config: { tableName: 'quotations', searchColumns: ['quotation_number'] } },
  { prefix: '/api/quotation-items', config: { tableName: 'quotation_items', tenantScoped: false } },
  { prefix: '/api/invoices', config: { tableName: 'invoices', searchColumns: ['invoice_number'] } },
  { prefix: '/api/invoice-items', config: { tableName: 'invoice_items', tenantScoped: false } },
  { prefix: '/api/estimates', config: { tableName: 'estimates', searchColumns: ['estimate_number'] } },
  { prefix: '/api/estimate-items', config: { tableName: 'estimate_items', tenantScoped: false } },
  { prefix: '/api/deal-activities', config: { tableName: 'deal_activities', tenantScoped: false } },
  { prefix: '/api/deal-products', config: { tableName: 'deal_products', tenantScoped: false } },
  { prefix: '/api/deal-registrations', config: { tableName: 'deal_registrations' } },
  { prefix: '/api/deal-stage-log', config: { tableName: 'deal_stage_progression_log', tenantScoped: false } },
  { prefix: '/api/employee-requests', config: { tableName: 'employee_requests', searchColumns: ['title'], userOwned: true } },
  { prefix: '/api/leave-requests', config: { tableName: 'leave_requests', userOwned: true } },
  { prefix: '/api/leave-policies', config: { tableName: 'leave_policies' } },
  { prefix: '/api/leave-balances', config: { tableName: 'leave_balances', userOwned: true } },
  { prefix: '/api/expense-reports', config: { tableName: 'expense_reports', userOwned: true } },
  { prefix: '/api/expense-items', config: { tableName: 'expense_items', tenantScoped: false } },
  { prefix: '/api/expense-categories', config: { tableName: 'expense_categories' } },
  { prefix: '/api/travel-requests', config: { tableName: 'travel_requests', userOwned: true } },
  { prefix: '/api/travel-bookings', config: { tableName: 'travel_bookings', tenantScoped: false } },
  { prefix: '/api/renewals', config: { tableName: 'renewals', searchColumns: ['name'] } },
  { prefix: '/api/sales-teams', config: { tableName: 'sales_teams', searchColumns: ['name'] } },
  { prefix: '/api/sales-team-members', config: { tableName: 'sales_team_members', tenantScoped: false } },
  { prefix: '/api/sales-targets', config: { tableName: 'sales_targets' } },
  { prefix: '/api/sales-territories', config: { tableName: 'sales_territories' } },
  { prefix: '/api/sales-forecasts', config: { tableName: 'sales_forecasts', userOwned: true } },
  { prefix: '/api/inside-sales-prospects', config: { tableName: 'inside_sales_prospects', searchColumns: ['company_name', 'contact_name'] } },
  { prefix: '/api/leads', config: { tableName: 'leads', searchColumns: ['name', 'email', 'company'], userOwned: true } },
  { prefix: '/api/projects', config: { tableName: 'projects', searchColumns: ['name', 'project_number'] } },
  { prefix: '/api/project-tasks', config: { tableName: 'project_tasks', searchColumns: ['title'], tenantScoped: false } },
  { prefix: '/api/project-members', config: { tableName: 'project_members', tenantScoped: false } },
  { prefix: '/api/project-milestones', config: { tableName: 'project_milestones', tenantScoped: false } },
  { prefix: '/api/project-documents', config: { tableName: 'project_documents', tenantScoped: false } },
  { prefix: '/api/tenders', config: { tableName: 'tenders', searchColumns: ['title', 'tender_number'] } },
  { prefix: '/api/tender-documents', config: { tableName: 'tender_documents', tenantScoped: false } },
  { prefix: '/api/sops', config: { tableName: 'sops', searchColumns: ['title'] } },
  { prefix: '/api/customer-support-contracts', config: { tableName: 'customer_support_contracts', searchColumns: ['contract_name'] } },
  { prefix: '/api/customer-support-tickets', config: { tableName: 'customer_support_tickets', searchColumns: ['title', 'ticket_number'] } },
  { prefix: '/api/customer-deliveries', config: { tableName: 'customer_deliveries' } },
  { prefix: '/api/notifications', config: { tableName: 'notifications', userOwned: true } },
  { prefix: '/api/profiles', config: { tableName: 'profiles', searchColumns: ['full_name', 'email'], userOwned: true, userField: 'user_id' } },
  { prefix: '/api/user-roles', config: { tableName: 'user_roles', tenantScoped: false } },
  { prefix: '/api/user-teams', config: { tableName: 'user_teams', tenantScoped: false } },
  { prefix: '/api/tenant-members', config: { tableName: 'tenant_members' } },
  { prefix: '/api/tenants', config: { tableName: 'tenants', searchColumns: ['name'], tenantScoped: false } },
  { prefix: '/api/tenant-modules', config: { tableName: 'tenant_modules' } },
  { prefix: '/api/module-definitions', config: { tableName: 'module_definitions', tenantScoped: false } },
  { prefix: '/api/account-groups', config: { tableName: 'account_groups', searchColumns: ['name'] } },
  { prefix: '/api/ledger-accounts', config: { tableName: 'ledger_accounts', searchColumns: ['name', 'code'] } },
  { prefix: '/api/voucher-types', config: { tableName: 'voucher_types', searchColumns: ['name'] } },
  { prefix: '/api/vouchers', config: { tableName: 'vouchers' } },
  { prefix: '/api/voucher-entries', config: { tableName: 'voucher_entries', tenantScoped: false } },
  { prefix: '/api/budgets', config: { tableName: 'budgets', searchColumns: ['name'] } },
  { prefix: '/api/budget-items', config: { tableName: 'budget_items', tenantScoped: false } },
  { prefix: '/api/currencies', config: { tableName: 'currencies' } },
  { prefix: '/api/cost-centers', config: { tableName: 'cost_centers', searchColumns: ['name'] } },
  { prefix: '/api/bank-reconciliation', config: { tableName: 'bank_reconciliation' } },
  { prefix: '/api/day-book-entries', config: { tableName: 'day_book_entries' } },
  { prefix: '/api/fiscal-years', config: { tableName: 'fiscal_years' } },
  { prefix: '/api/stock-items', config: { tableName: 'stock_items', searchColumns: ['name'] } },
  { prefix: '/api/stock-groups', config: { tableName: 'stock_groups', searchColumns: ['name'] } },
  { prefix: '/api/inventory-items', config: { tableName: 'inventory_items', searchColumns: ['name', 'sku'] } },
  { prefix: '/api/gst-transactions', config: { tableName: 'gst_transactions' } },
  { prefix: '/api/gst-returns', config: { tableName: 'gst_returns' } },
  { prefix: '/api/product-catalog', config: { tableName: 'product_catalog', searchColumns: ['name', 'sku'] } },
  { prefix: '/api/vendors', config: { tableName: 'vendors', searchColumns: ['name'] } },
  { prefix: '/api/distributors', config: { tableName: 'distributors', searchColumns: ['name'] } },
  { prefix: '/api/job-postings', config: { tableName: 'job_postings', searchColumns: ['title'] } },
  { prefix: '/api/job-applicants', config: { tableName: 'job_applicants', searchColumns: ['name', 'email'] } },
  { prefix: '/api/hr-workflows', config: { tableName: 'hr_workflows' } },
  { prefix: '/api/onboarding-requests', config: { tableName: 'onboarding_requests' } },
  { prefix: '/api/resignation-requests', config: { tableName: 'resignation_requests', userOwned: true } },
  { prefix: '/api/employee-documents', config: { tableName: 'employee_documents', userOwned: true } },
  { prefix: '/api/employee-events', config: { tableName: 'employee_events' } },
  { prefix: '/api/employee-certifications', config: { tableName: 'employee_certifications', userOwned: true } },
  { prefix: '/api/daily-activities', config: { tableName: 'daily_activities', userOwned: true } },
  { prefix: '/api/presales-opportunities', config: { tableName: 'presales_opportunities' } },
  { prefix: '/api/poc-requests', config: { tableName: 'poc_requests' } },
  { prefix: '/api/demo-schedules', config: { tableName: 'demo_schedules' } },
  { prefix: '/api/payment-records', config: { tableName: 'payment_records' } },
  { prefix: '/api/post-sale-workflows', config: { tableName: 'post_sale_workflows' } },
  { prefix: '/api/accounts-workflows', config: { tableName: 'accounts_workflows' } },
  { prefix: '/api/order-processing-requests', config: { tableName: 'order_processing_requests' } },
  { prefix: '/api/legal-documents', config: { tableName: 'legal_documents', searchColumns: ['title'] } },
  { prefix: '/api/email-templates', config: { tableName: 'email_templates', searchColumns: ['name'] } },
  { prefix: '/api/email-sequences', config: { tableName: 'email_sequences', searchColumns: ['name'] } },
  { prefix: '/api/document-templates', config: { tableName: 'document_templates', searchColumns: ['name'] } },
  { prefix: '/api/training-sessions', config: { tableName: 'training_sessions', searchColumns: ['title'] } },
  { prefix: '/api/learning-courses', config: { tableName: 'learning_courses', searchColumns: ['title'] } },
  { prefix: '/api/approval-workflows', config: { tableName: 'approval_workflows', tenantScoped: false } },
  { prefix: '/api/canned-responses', config: { tableName: 'canned_responses', searchColumns: ['title'] } },
  { prefix: '/api/cybersecurity-news', config: { tableName: 'cybersecurity_news', searchColumns: ['title'] } },
  { prefix: '/api/cynet-licenses', config: { tableName: 'cynet_licenses', searchColumns: ['site_name'] } },
  { prefix: '/api/integrations', config: { tableName: 'integrations', searchColumns: ['name'] } },
  { prefix: '/api/team-chat-messages', config: { tableName: 'team_chat_messages' } },
  { prefix: '/api/team-reminders', config: { tableName: 'team_reminders', userOwned: true } },
  { prefix: '/api/video-calls', config: { tableName: 'video_calls' } },
  { prefix: '/api/remote-sessions', config: { tableName: 'remote_sessions' } },
  { prefix: '/api/landing-pages', config: { tableName: 'landing_pages', searchColumns: ['title'] } },
  { prefix: '/api/web-form-captures', config: { tableName: 'web_form_captures' } },
  { prefix: '/api/marketing-journeys', config: { tableName: 'marketing_journeys', searchColumns: ['name'] } },
  { prefix: '/api/sales-automations', config: { tableName: 'sales_automations', searchColumns: ['name'] } },
  { prefix: '/api/rotten-deal-settings', config: { tableName: 'rotten_deal_settings' } },
  { prefix: '/api/tenant-audit-log', config: { tableName: 'tenant_audit_log' } },
  { prefix: '/api/tenant-invitations', config: { tableName: 'tenant_invitations' } },
  { prefix: '/api/organization-settings', config: { tableName: 'organization_settings', tenantScoped: false } },
  { prefix: '/api/organization-notes', config: { tableName: 'organization_notes', tenantScoped: false } },
  { prefix: '/api/organization-meetings', config: { tableName: 'organization_meetings', tenantScoped: false } },
  { prefix: '/api/organization-tasks', config: { tableName: 'organization_tasks', tenantScoped: false } },
  { prefix: '/api/support-slas', config: { tableName: 'support_slas' } },
  { prefix: '/api/oem-technologies', config: { tableName: 'oem_technologies', searchColumns: ['name'] } },
  { prefix: '/api/contact-lifecycle-stages', config: { tableName: 'contact_lifecycle_stages' } },
  { prefix: '/api/notification-preferences', config: { tableName: 'notification_preferences', tenantScoped: false, userOwned: true } },
];

export function registerAllCrudRoutes(app: any) {
  for (const { prefix, config } of allRouteConfigs) {
    app.register(createCrudRoutes(config), { prefix });
  }
}
